"""Manage CLAUDE.md context files for milestone execution."""

from __future__ import annotations

import logging
import shutil
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from imaro.models.schemas import IntentionDocument, Milestone, MilestoneResult

logger = logging.getLogger(__name__)

CLAUDE_MD = "CLAUDE.md"
BACKUP_NAME = "CLAUDE.md.backup"
IMARO_DIR = ".imaro"


class ContextManager:
    """Write and restore CLAUDE.md with intention-aware context."""

    def write_context(
        self,
        milestone: Milestone,
        intention: IntentionDocument,
        project_path: Path,
        previous_milestones: list[MilestoneResult] | None = None,
    ) -> None:
        """Write a CLAUDE.md tailored to the current milestone."""
        self.backup_context(project_path)

        mapping = milestone.intention_mapping
        lines = [
            "# Project Context (auto-generated by IMARO)",
            "",
            "## Project Intention",
            f"**Purpose:** {intention.purpose}",
            f"**Core Value:** {intention.core_value}",
            f"**Target Users:** {intention.target_users}",
            "",
            "## Current Milestone",
            f"**{milestone.id}: {milestone.name}**",
            "",
            milestone.description,
            "",
            "### Scope",
            *[f"- {s}" for s in milestone.scope],
            "",
            "### Acceptance Criteria",
            *[f"- {c}" for c in milestone.acceptance_criteria],
            "",
            "### Constraints",
            *[f"- {c}" for c in milestone.constraints],
            "",
            "### Intention Mapping",
            f"- Serves Purpose: {mapping.serves_purpose}",
            f"- Serves Core Value: {mapping.serves_core_value}",
            "- Fulfills Requirements:",
            *[f"  - {r}" for r in mapping.fulfills_requirements],
            "- Success Criteria Addressed:",
            *[f"  - {s}" for s in mapping.success_criteria_addressed],
        ]

        if previous_milestones:
            lines.extend(["", "## Previous Milestones"])
            for mr in previous_milestones:
                if mr.milestone:
                    lines.append(
                        f"- **{mr.milestone.id}: {mr.milestone.name}** — {mr.status.value}"
                    )

        lines.extend([
            "",
            "## Judgment Criteria",
            "Your code will be reviewed against these criteria:",
            "1. Does it fulfill the acceptance criteria listed above?",
            "2. Does it stay within the defined scope and constraints?",
            "3. Does it serve the project's purpose and core value?",
            "4. Is it consistent with the intention mapping?",
        ])

        content = "\n".join(lines) + "\n"
        (project_path / CLAUDE_MD).write_text(content, encoding="utf-8")
        logger.debug("Wrote CLAUDE.md for milestone %s", milestone.id)

    def backup_context(self, project_path: Path) -> None:
        """Back up existing CLAUDE.md if present."""
        source = project_path / CLAUDE_MD
        if source.exists():
            dest_dir = project_path / IMARO_DIR
            dest_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(str(source), str(dest_dir / BACKUP_NAME))
            logger.debug("Backed up CLAUDE.md")

    def restore_context(self, project_path: Path) -> None:
        """Restore the original CLAUDE.md from backup."""
        backup = project_path / IMARO_DIR / BACKUP_NAME
        target = project_path / CLAUDE_MD
        if backup.exists():
            shutil.copy2(str(backup), str(target))
            backup.unlink()
            logger.debug("Restored CLAUDE.md from backup")
        elif target.exists():
            target.unlink()
            logger.debug("Removed IMARO-generated CLAUDE.md")
